# Generated by Django 3.1.7 on 2021-03-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('employee_ID', models.IntegerField()),
                ('team', models.CharField(max_length=100)),
                ('hourly_rate', models.FloatField()),
            ],
        ),
    ]
