# Generated by Django 3.1.7 on 2021-03-14 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamemployee',
            name='employee_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee_id', to='pages.employee'),
        ),
        migrations.AlterField(
            model_name='teamemployee',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_id', to='pages.team'),
        ),
    ]
